apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rknpu-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: rknpu-dp-ds
  template:
    metadata:
      labels:
        name: rknpu-dp-ds
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      priorityClassName: system-node-critical
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      containers:
      - image: ghcr.io/elct9620/rknpu-device-plugin
        name: rknpu-dp-cntr
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
          - name: dp
            mountPath: /var/lib/kubelet/device-plugins
          - name: sys
            mountPath: /sys
          - name: dev
            mountPath: /dev
      volumes:
        - name: dp
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: sys
          hostPath:
            path: /sys
        - name: dev
          hostPath:
            path: /dev

